name: Example CI

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.3.0
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings --no-deps

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - os: macos-11
            target: x86_64-apple-darwin
          # - os: windows-2019
          #   target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2.3.0
        with:
          key: ${{ matrix.target }}
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Build
        run: cargo build --target ${{ matrix.target }}
      - name: Run tests
        env:
          RUST_BACKTRACE: 1
        run: cargo test --workspace --target ${{ matrix.target }}
